### ISSUE TITLE
Shopping App Website: cleanup

### ISSUE THREAD

**Issue by hacksparrow** [loopbackio/loopback4-example-shopping#478]
Sundry list of tasks for the shopping app.

- [ ] Get rid of jQuery and use native browser APIs
- [x] Use async/await instead of callbacks
- [ ] Use ES6 template literals for templates
- [ ] Inject passwordHasher - https://github.com/strongloop/loopback4-example-shopping/pull/468#discussion_r366646796

Miroslav was considering a build pipeline for the website. However, I am not in favor of it. Let's keep things simple; the less dependencies and steps, the better.

**Comment by bajtos** [comment]
> Use ES6 template literals for templates

I think the easiest option is to use Handlebars for templating, see https://handlebarsjs.com. You can add the library to your front-page via a public CDN and it will handle tricky parts of HTML escaping for you.

**Comment by mrmodise** [comment]
Just wondering on my end, would using Vue.js or a similar library not make it easy for most people to understand? I just feel handlebars will make it a bit difficult for most to understand due to its lack of documentation compared to newer libraries 😄

**Comment by dougal83** [comment]
@mrmodise IMO handlebars focus on templating makes it a good candidate for a simple example. That being said that does not stop any enthusiastic contributor making a package for an alternative front end example. Personally I would like to find enough time to flesh out an angular implementation.

**Comment by mrmodise** [comment]
> @mrmodise IMO handlebars focus on templating makes it a good candidate for a simple example. That being said that does not stop any enthusiastic contributor making a package for an alternative front end example. Personally I would like to find enough time to flesh out an angular implementation.

I thought Angular would be a NO since its more complex but on a personal level you and I are on the same page. Shameless plug, I prefer Angular 😆

**Comment by mrmodise** [comment]
> @mrmodise IMO handlebars focus on templating makes it a good candidate for a simple example. That being said that does not stop any enthusiastic contributor making a package for an alternative front end example. 

I would be that enthusiastic contributor. I just think the newer frameworks will also increase visibility on the project since it will ride off the glory of modern frameworks. We need the numbers 😃
