### ISSUE TITLE
Shopping App Website: automated API client generation for the frontend

### ISSUE THREAD

**Issue by hacksparrow** [loopbackio/loopback4-example-shopping#479]
Quoting @bajtos https://github.com/strongloop/loopback4-example-shopping/pull/468#discussion_r364603261

> For longer term, it would be great to leverage OpenAPI spec provided by the server and use either a code-generated client (see https://github.com/OpenAPITools/openapi-generator) or at least a dynamic client https://github.com/swagger-api/swagger-js. This part is of scope of this pull request though.

**Comment by dougal83** [comment]
@hacksparrow Would you like me to set up an example of the [JavaScript generator](https://openapi-generator.tech/docs/generators/javascript) (or one of the other options)?

**Comment by dhmlau** [comment]
A reference project from @joschne: https://github.com/joschne/loopback4-example-ngx-sdk.
